name: pet_plan_pruebas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  carousel_slider: ^5.0.0
  
  url_launcher: ^6.1.14
  google_generative_ai: ^0.4.6
  supabase_flutter: ^2.8.4
  grouped_list: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/